version: "3.9"

services:
  widget_service:
    container_name: widget-service
    image: nastyakirry/widget-service:1.0
    restart: always
    command: [
          "bash -c 'touch /widget.jar'"
      ]
    environment:
      KEYCLOAK_JSON_PATH: file:keycloak.json
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app
    depends_on:
      - "postgres"
    ports:
      - "8086:8086"
    networks:
      - backend
  postgres:
    container_name: postgres
    image: "postgres:13.2"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:rw
    env_file:
      - ./database.dev.env
    ports:
      - "5444:5432"
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:5.1"
    env_file:
      - ./database.dev.env
    ports:
      - "5053:80"
    networks:
      - backend
  keycloak:
    container_name: auth-service
    image: quay.io/keycloak/keycloak:20.0.3
    command: [
        "start-dev",
        "--import-realm",
        "--features=declarative-user-profile"
    ]
    restart: always
    volumes:
      - ./kc-property/kc-auth-realm-realm.json:/opt/keycloak/data/import/kc-auth-realm-realm.json:ro
    env_file:
      - ./keycloak.dev.env
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend
  widget-main:
    container_name: widget-main-widget
    image: fort163/widget-main:1.0
    ports:
      - "3001:3001"
    networks:
      - backend
  currency-service:
    container_name: currency-service
    image: anedomets/currency:1.0
    restart: always
    command: [
        "bash -c 'touch /app.jar'"
    ]
    environment:
      KEYCLOAK_JSON_PATH: file:keycloak.json
    ports:
      - "8010:8010"
    networks:
      - backend
  currency-widget:
    container_name: currency-widget
    image: anedomets/currency-widget:1.0
    ports:
      - "3010:3010"
    networks:
      - backend
  message-service:
    container_name: message-service
    image: ivanedovin/message-service:1.0
    restart: always
    environment:
      KEYCLOAK_JSON_PATH: file:keycloak.json
    command: [
        "bash -c 'touch /resource.jar'"
    ]
    ports:
      - "8020:8020"
    networks:
      - backend
  message-widget:
    container_name: message-widget
    image: ivanedovin/message-widget:1.0
    ports:
      - "3020:3020"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge